
import PostList from "@/components/PostList";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};


export default async function Home() {




  return (
    <div>

      <h1>Hello Jee</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fuga, voluptate, maiores harum distinctio incidunt, quo non obcaecati in autem dolorum nobis nam. Iusto et reprehenderit nihil laboriosam voluptates, provident quaerat?</p>


      <Suspense fallback={<div>Loading...</div>}>
        <PostList />


      </Suspense>






    </div>
  )
}