
import DeleteEmployee from "@/components/DeleteEmployee";
import PostList from "@/components/PostList";
import { Button } from "@/components/ui/button";
import { Employee } from "@/models/Employee";
import axios from "axios";
import { EditIcon } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};


export default async function Home() {

  const response = await axios.get('https://69ad5193b50a169ec87f232e.mockapi.io/employees');
  const employees: Employee[] = response.data;


  return (
    <div className="grid grid-cols-4 gap-5">

      {employees.map((employee) => (
        <div key={employee.id} className="border-2 p-3">
          <h5>{employee.name}</h5>
          <p>{employee.age}</p>
          <p>{employee.occupation}</p>

          <div className="flex justify-end">
            <Link href={`/employee/edit/${employee.id}`} >
              <Button variant={'ghost'}>

                <EditIcon />

              </Button>


            </Link>
            <DeleteEmployee id={employee.id} />
          </div>
        </div>
      ))}

      {/* <h1>Hello Jee</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fuga, voluptate, maiores harum distinctio incidunt, quo non obcaecati in autem dolorum nobis nam. Iusto et reprehenderit nihil laboriosam voluptates, provident quaerat?</p> */}

      {/* 
      <Suspense fallback={<div>Loading...</div>}>
        <PostList />


      </Suspense> */}






    </div>
  )
}